configuration:
  width: 450
  height: 450
  luminosity-label: '%1$.1f fb^{-1} (13 TeV)'
  experiment: " CMS"
  experiment-label-paper: true
  extra-label: "Preliminary"
  root: ''
  luminosity: 59832
  #luminosity-error: 0.025
  error-fill-style: 3254
  error-fill-color: "#ee556270"
  staterror-fill-style: 3145
  staterror-fill-color: 7
  ratio-fit-error-fill-style: 1001
  ratio-fit-error-fill-color: "#aa556270"
  ratio-fit-line-color: "#0B486B"
  blinded-range-fill-color: "#29556270"
  blinded-range-fill-style: 1001
  yields-table-align: v
  book-keeping-file: 'plots.root'
  yields-table-numerical-precision-yields: 2

files: 
  include: ['files_2018_HEM.yml']

systematics:

plots:
  #include: ['histos_control.yml', 'histos_reco.yml', 'histos_yield.yml']
  include: ['histos_control.yml', 'histos_yield.yml']

legend:
  #position: [0.18, 0.70, 0.96, 0.88]
  position: [0.35, 0.70, 0.96, 0.88]
  columns: 4

groups:
  include: ['groups.yml']
