'h_dnn_pred':
  x-axis: "DNN Score"
  y-axis: "Entries"
  y-axis-format: "%1% / %2$.2f"
  log-y: true
  sort-by-yields: true
  save-extensions: ['pdf']
  for-yields: true
  yields-table-order: 0
  yields-title: 'DNN'
  ratio-y-axis-range: [0.01, 2]
  ratio-y-axis-auto-range: false
  signal-normalize-data: false
  blinded-range: [2.501,100]
# log-x: true
#  rebin: 4
#  labels:
#    - {text: 'b2j3', position: [0.781, 0.806], size: 18}

